### ISSUE TITLE
I want to translate Flexia to Turkish

### ISSUE THREAD

**Issue by Frkn64** [rupok/flexia#16]
Hi, I am using Flexia for a while. I translated the some theme files to Turkish for my website, but when Flexia is updated, the changes I made are resetting. 

In short, I want to translate Flexia into Turkish language. I have made a few translations through the Wordpress translation page, but it has not been approved. If approved, I will continue and translate all of them into Turkish.
My translations is here: https://translate.wordpress.org/locale/tr/default/wp-themes/flexia

I am sorry if I am writing this to wrong place. I couldn't find another place to write.

**Comment by rupok** [comment]
Hello @Frkn64 

Thanks for your contribution. I see your translation and those need to be approved by the moderator (Translation Editor) of your community. You can communicate with them to faster the process. And you can also complete the translation and let me know so that I can add them within the theme.

Cheers!
